import AppKit
import Observation

enum PanelSection: String, CaseIterable {
    case queue = "Queue", history = "History", settings = "Settings"
}

@MainActor @Observable
final class ClipboardModel {
    var history: [Clip] = []
    var queue: [Clip] = []
    var section: PanelSection = .queue
    var search = ""
    var isPaused = false
    var isCollecting = true
    var isBusy = false
    var status = "Copy a few things. Paste them in order."
    var suggestions: [Clip] = []
    var suggestedID: UUID?
    var targetLabel = ""
    var lastSent: Clip?
    var apiKeyDraft = ""
    var hasAPIKey = false
    var keyFromDotEnv = false
    var accessibilityEnabled = TargetAccess.isTrusted
    var shortcuts = ShortcutSettings.load()
    var shortcutError: String?
    var unavailableShortcuts: [ShortcutAction: String] = [:]

    var cloudEnabled = UserDefaults.standard.bool(forKey: "cloudEnabled") {
        didSet {
            UserDefaults.standard.set(cloudEnabled, forKey: "cloudEnabled")
            if !cloudEnabled { cancelPending() }
        }
    }
    var rememberHistory = UserDefaults.standard.bool(forKey: "rememberHistory") {
        didSet {
            UserDefaults.standard.set(rememberHistory, forKey: "rememberHistory")
            saveHistory()
        }
    }
    var autoPaste = UserDefaults.standard.bool(forKey: "autoPaste") {
        didSet { UserDefaults.standard.set(autoPaste, forKey: "autoPaste") }
    }
    var excludedApps = UserDefaults.standard.string(forKey: "excludedApps") ?? "" {
        didSet { UserDefaults.standard.set(excludedApps, forKey: "excludedApps") }
    }

    @ObservationIgnored var showPanel: (() -> Void)?
    @ObservationIgnored var hidePanel: (() -> Void)?
    @ObservationIgnored var changeShortcut: ((ShortcutAction, Shortcut) -> Void)?
    @ObservationIgnored var resetShortcuts: (() -> Void)?
    @ObservationIgnored var savedTarget: PasteTarget?
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var clipboardCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var requestID = UUID()
    @ObservationIgnored private var key: String?

    private static let passwordApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop",
        "com.apple.Passwords", "com.apple.keychainaccess", "com.dashlane.Dashlane",
        "com.keepassxc.keepassxc", "org.keepassxc.keepassxc", "com.lastpass.LastPass"
    ]
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
    ]
    private var historyURL: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Mneme/history.json")
    }

    var visibleClips: [Clip] {
        let clips = section == .queue ? queue : history
        return search.isEmpty ? clips : clips.filter {
            $0.text.localizedCaseInsensitiveContains(search) || $0.source.localizedCaseInsensitiveContains(search)
        }
    }

    func start() {
        if rememberHistory, let data = try? Data(contentsOf: historyURL),
           let clips = try? JSONDecoder().decode([Clip].self, from: data) {
            history = Array(clips.prefix(200))
        }
        do { try refreshAPIKey() }
        catch { status = error.localizedDescription }
        timer = Timer.scheduledTimer(withTimeInterval: 0.35, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.pollClipboard() }
        }
    }

    func stop() { timer?.invalidate(); timer = nil; cancelPending() }

    func pollClipboard() {
        accessibilityEnabled = TargetAccess.isTrusted
        let board = NSPasteboard.general
        guard board.changeCount != clipboardCount else { return }
        clipboardCount = board.changeCount
        guard !isPaused,
              Set((board.types ?? []).map(\.rawValue)).isDisjoint(with: Self.ignoredTypes) else { return }
        let app = NSWorkspace.shared.frontmostApplication
        let bundle = app?.bundleIdentifier ?? ""
        let userExclusions = Set(excludedApps.split(whereSeparator: { $0 == "," || $0.isNewline })
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) })
        guard bundle != Bundle.main.bundleIdentifier,
              !Self.passwordApps.contains(bundle), !userExclusions.contains(bundle),
              let text = board.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.utf8.count <= 64_000, !Self.looksLikeSecret(text) else { return }
        let clip = Clip(text: text, source: app?.localizedName ?? "Unknown app")
        history.insert(clip, at: 0)
        if history.count > 200 { history.removeLast(history.count - 200) }
        if isCollecting {
            if queue.count < 100 { queue.append(clip) }
            else { status = "Queue is full (100 items). The copy is still in History." }
        }
        saveHistory()
    }

    // A small local filter, not a guarantee that every kind of secret is detected.
    private static func looksLikeSecret(_ text: String) -> Bool {
        text.contains("PRIVATE KEY-----") || text.range(
            of: #"(?:^|\s)(?:sk-[A-Za-z0-9_-]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})"#,
            options: .regularExpression
        ) != nil
    }

    @discardableResult
    func writeClipboard(_ text: String) -> Bool {
        let board = NSPasteboard.general
        board.clearContents()
        let success = board.setString(text, forType: .string)
        clipboardCount = board.changeCount
        return success
    }

    func copy(_ clip: Clip) {
        status = writeClipboard(clip.text) ? "Copied. Use ⌘V in any app." : "Could not write to the clipboard."
    }

    func enqueue(_ clip: Clip) {
        guard queue.count < 100 else { status = "Queue is full (100 items)."; return }
        // Give repeated uses of the same historical item independent queue identities.
        queue.append(Clip(text: clip.text, source: clip.source))
        status = "Added to the end of the queue."
    }

    func remove(_ clip: Clip) {
        cancelPending()
        if section == .queue { queue.removeAll { $0.id == clip.id } }
        else { history.removeAll { $0.id == clip.id }; saveHistory() }
        suggestions.removeAll { $0.id == clip.id }
    }

    func move(_ clip: Clip, by offset: Int) {
        guard let index = queue.firstIndex(where: { $0.id == clip.id }),
              queue.indices.contains(index + offset) else { return }
        cancelPending()
        queue.swapAt(index, index + offset)
    }

    func clearQueue() {
        cancelPending(); queue.removeAll(); suggestions.removeAll(); lastSent = nil
        status = "Queue cleared. New copies will be collected if collection is on."
    }

    func clearAll() {
        clearQueue(); history.removeAll(); saveHistory(); status = "History and queue cleared."
    }

    func restoreLast() {
        guard let clip = lastSent, queue.count < 100 else { return }
        queue.insert(clip, at: 0); lastSent = nil
        status = "Returned the last item to the front of the queue."
    }

    func saveKey() {
        let value = apiKeyDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty else { status = "Enter a TypeSafe API key first."; return }
        do {
            try Keychain.save(value)
            apiKeyDraft = ""
            try refreshAPIKey()
            status = keyFromDotEnv ? "Saved in Keychain. Your .env key takes precedence." : "API key saved in Keychain."
        } catch { status = error.localizedDescription }
    }

    func deleteKey() {
        do {
            try Keychain.delete()
            try refreshAPIKey()
            if !hasAPIKey { cloudEnabled = false }
            status = keyFromDotEnv ? "Keychain key removed. Your .env key is still available." : "API key removed."
        } catch { status = error.localizedDescription }
    }

    func refreshAPIKey() throws {
        // Do not keep a stale key after the file is removed or becomes invalid.
        key = nil; hasAPIKey = false; keyFromDotEnv = false
        if let configured = try DotEnv.apiKey() {
            key = configured; keyFromDotEnv = true
        } else {
            key = try Keychain.read()
        }
        hasAPIKey = key != nil
    }

    func grantAccessibility() {
        TargetAccess.requestPermission()
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
            NSWorkspace.shared.open(url)
        }
    }

    func pasteNext(fromPanel: Bool = false) {
        guard let clip = queue.first else { status = "Queue is empty. Copy something first."; showPanel?(); return }
        paste(clip, fromPanel: fromPanel)
    }

    func paste(_ clip: Clip, fromPanel: Bool = true) {
        guard !isBusy else { return }
        isBusy = true
        let token = UUID(); requestID = token
        Task { @MainActor in
            defer { if requestID == token { isBusy = false } }
            do {
                let target = try await prepareTarget(fromPanel: fromPanel)
                guard requestID == token else { return }
                try dispatch(clip, target: target)
            } catch { status = error.localizedDescription; showPanel?() }
        }
    }

    func smartPaste(fromPanel: Bool = false) {
        guard !isBusy else { return }
        do { try refreshAPIKey() }
        catch { section = .settings; status = error.localizedDescription; showPanel?(); return }
        guard cloudEnabled, let key else {
            section = .settings; status = "Set TYPESAFE_API_KEY in .env or save a key here, then enable Smart Paste."; showPanel?(); return
        }
        // While a queue exists, do not revive old history items already consumed from it.
        let pool = Array((queue.isEmpty ? history : queue).prefix(12))
        guard !pool.isEmpty else { status = "Copy some text first."; showPanel?(); return }
        suggestions.removeAll(); suggestedID = nil
        isBusy = true
        let token = UUID(); requestID = token
        Task { @MainActor in
            defer { if requestID == token { isBusy = false } }
            do {
                let target = try await prepareTarget(fromPanel: fromPanel)
                guard requestID == token, cloudEnabled else { return }
                savedTarget = target; targetLabel = target.context.displayName
                guard target.context.hasClues else {
                    suggestions = pool; section = .queue
                    status = "This field has no readable label. Choose an item below."; showPanel?(); return
                }
                status = "Finding a match for \(target.context.displayName)…"
                let result = try await SmartMatcher.match(MatchRequest(
                    apiKey: key, field: target.context, candidates: pool.map(Candidate.init)
                ))
                guard requestID == token, cloudEnabled else { return }
                guard TargetAccess.isStillFocused(target) else {
                    status = "Focus changed while matching. Nothing was pasted."; showPanel?(); return
                }
                guard let choice = result.choice, choice != "none",
                      let selected = pool.first(where: { $0.id.uuidString == choice }) else {
                    suggestions = pool; section = .queue
                    status = "No clear match for \(target.context.displayName). Choose an item."; showPanel?(); return
                }
                let confidence = result.confidence ?? 0
                let probability = result.probabilities?[choice] ?? 0
                let runnerUp = result.probabilities?.filter { $0.key != choice }.map(\.value).max() ?? 1
                // Conservative provisional thresholds; confidence is not an accuracy guarantee.
                if autoPaste && selected.text.unicodeScalars.count <= 1_200
                    && confidence >= 0.85 && probability >= 0.90 && probability - runnerUp >= 0.25 {
                    try dispatch(selected, target: target)
                } else {
                    suggestions = [selected] + pool.filter { $0.id != selected.id }
                    suggestedID = selected.id
                    section = .queue
                    status = "Suggested match for \(target.context.displayName). Choose Paste to use it."
                    showPanel?()
                }
            } catch {
                guard requestID == token else { return }
                status = error.localizedDescription; showPanel?()
            }
        }
    }

    func cancelPending() { requestID = UUID(); isBusy = false }

    private func prepareTarget(fromPanel: Bool) async throws -> PasteTarget {
        if fromPanel {
            guard let target = savedTarget, !target.app.isTerminated else {
                throw MnemeError.message("Focus the destination field, then use \(shortcuts.smart.label) for Smart Paste or \(shortcuts.next.label) for paste next.")
            }
            NSApp.yieldActivation(to: target.app)
            hidePanel?()
            target.app.activate(options: [])
            try await Task.sleep(for: .milliseconds(160))
            guard TargetAccess.isStillFocused(target) else {
                throw MnemeError.message("The destination field changed. Focus it and use the shortcut again.")
            }
            return target
        }
        return try TargetAccess.capture()
    }

    private func dispatch(_ clip: Clip, target: PasteTarget) throws {
        try TargetAccess.paste(clip.text, into: target, writeClipboard: writeClipboard)
        if queue.contains(where: { $0.id == clip.id }) {
            queue.removeAll { $0.id == clip.id }; lastSent = clip
        }
        suggestions.removeAll()
        status = "Paste sent to \(target.context.app). \(queue.count) items left in queue."
    }

    private func saveHistory() {
        do {
            if !rememberHistory {
                if FileManager.default.fileExists(atPath: historyURL.path) { try FileManager.default.removeItem(at: historyURL) }
                return
            }
            let folder = historyURL.deletingLastPathComponent()
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true,
                                                    attributes: [.posixPermissions: 0o700])
            try JSONEncoder().encode(history).write(to: historyURL, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: historyURL.path)
        } catch { status = "History could not be saved. Copies remain available for this session." }
    }
}
